### ISSUE TITLE
Phpunit

### ISSUE THREAD

**Issue by sergeyklay** [trntv/systeminfo#11]
Предлагаю написать Unit-тесты, и добавить интеграцию с Travis CI.
Кстати, можно сразу же проверять на PSR-стандарт (пример конфига https://github.com/phalcon/incubator/blob/master/.travis.yml)

**Comment by trntv** [comment]
Да, и юнит тесты нужны (для того и планирую вынести в src) и CI использовать можно, но для начала надо что-то решить с виндой и возможно, разнести реализации под конкретную ОС по классам. Я, честно говоря делал этот пакет на скорую руку и планировал его развивать по мере необходимости в своих проектах :-)

Но сейчас подумываю над тем чтобы выкроить на него немного времени и привести в более презентабельный вид. 

Кстати, спасибо за участие, я рад благодарен за любые советы, обсуждение и помощь, будет желание и время - можете оформлять PR ;-)

**Comment by sergeyklay** [comment]
Для винды всё решаемо. По крайней мере серверной (где и будет использоваться SI). Просто надо обзавестись лицензионной копией серверной винды и поставить её себе в виртуалбоксе для тестов ;)
